### ISSUE TITLE
Primefaces overwrites all Datatable custom options

### ISSUE THREAD

**Issue by Yvtq8K3n** [TheCoder4eu/BootsFaces-OSP#1042]
This is the page whitout primefaces:
![image](https://user-images.githubusercontent.com/19397871/49826549-0fa5d400-fd7f-11e8-92ab-0d801a945ef3.png)

This is the page importing primefaces:
![image](https://user-images.githubusercontent.com/19397871/49826397-c5245780-fd7e-11e8-9d0d-97fe80bcd630.png)

Simply by importing primefaces i lost all functionaly the view has, Is there anything im missing or i can do? Thanks.

**Comment by stephanrauh** [comment]
Can you fill in some detail here? To me, it looks like the datatable isn't initialized at all. When you're talking about "custom options", did you refer to that?

And what did you do precisely?
* Did you add the PrimeFaces.jar to the class path? Which version?
* Did you add the PrimeFaces namespace to the JSF page?
* Did you add any PrimeFaces widget to the page? If so, which one?
* Is there any error message in the Java console or log?
* Is there any error message in the Browser's JavaScript console?

**Comment by Yvtq8K3n** [comment]
It seems when i import primefaces, all the datatable externals scripts stop being imported;_; so you have to import manualy one by one. Also it completly destroys your css.

**Comment by stephanrauh** [comment]
That doesn't sound as if you've found a solution. Mind you, we want to help you. We're just limited to our precious leisure time, because BootsFaces is a hobby project. 

If you send us a reproducer (i.e. a complete but simple program showing the bug without the need to configure anything, let alone a database), I'd love to have a look at it.

Best regards,
Stephan
