### ISSUE TITLE
Order of double in datatable

### ISSUE THREAD

**Issue by fdzaebel** [TheCoder4eu/BootsFaces-OSP#1065]
Hello team.

first of all: Thank you for your great BootsFaces job!

My problem: I cannot get double values to be ordered correctly when using an editable datatable. 

My jsf looks like this:

```
<b:dataTableColumn label="Deposit" order-by="dom-text-numeric" data-type="numeric" data-order="#{deposit.deposit}" data-search="#{deposit.deposit}">
   <b:inputText value="#{deposit.deposit}" size="7" validatorMessage="Wrong amount">
       		<f:validateDoubleRange minimum="0.0000000000000000001" />
   </b:inputText>     				
</b:dataTableColumn>
```

Deposit.Deposit is a simple "double" type.

The ordered result looks like this...

<img width="248" alt="bildschirmfoto 2019-03-02 um 09 15 33" src="https://user-images.githubusercontent.com/46503230/53679340-c903ae00-3ccb-11e9-8b46-7a4c3a9ea3f5.png">

Is this a bug or what am I doing wrong?

Thank your very much.

Frank.

**Comment by wgarbaya** [comment]
Hi Frank,
I think you have found a solution since...
Here is my code, I reproduced your case and than tried out different options :

`
<b:dataTableColumn  label="Deposit" data-order="#{deposit.amount}" data-search="#{deposit.amount}">
				<b:inputText value="#{deposit.amount}" size="7" validatorMessage="Wrong amount">
					<f:validateDoubleRange minimum="0.0000000000000000001" />
				</b:inputText>
			</b:dataTableColumn>`

https://github.com/wgarbaya/BootsFaces-OSP-issue-10651065

![image](https://user-images.githubusercontent.com/2361804/63974053-59b91c00-caac-11e9-828a-9e98c7c8328c.png)

Walid

**Comment by stephanrauh** [comment]
Seems like there's already a solution.
