### ISSUE TITLE
Enhancement: onerror onsuccess in commandButton

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#109]
Please add onsuccess and onerror event to commandButton to be able to choose proper action to execute.

**Comment by stephanrauh** [comment]
I've started to investigate this topic a couple of days ago. @bilak What's your definition of `onerror`? Standard JSF includes Java errors (such as `throw new NullPointerException()` somewhere in the controller bean), while PrimeFaces considers this a regular behavior and calls `onsuccess`. I suggest
* either to follow the standard JSF convention
* or to create a new error handler (`onerror`, `onjavaerror` and `onsuccess`).

What do you think?

**Comment by bilak** [comment]
Hi Stephan,
I used this with Primefaces (try to look there). From my point of view, if there is other result than success then it's error.

**Comment by stephanrauh** [comment]
I've implemented these two JavaScript callback functions for b:commandButton. However, the implementation is incomplete. The callback functions should be available to every AJAXified component, and they should pass parameters. I'll open a follow-up tickets because these features won't be part of version 0.8.2, but there's a lot to test.
