### ISSUE TITLE
Error in css in 0.6.7-SNAPSHOT

### ISSUE THREAD

**Issue by bilak** [TheCoder4eu/BootsFaces-OSP#110]
Hello, I'm currenty using newest snapshot (0.6.7). When primefaces fileupload is used on form, some strange css for is generated with it. If some input or button is under this element, it's not accessible by mouse click. 
In 0.6.6 version this is ok. This is not ok in Chrome and Firefox but ok in Safari.
![preview](http://i.imgur.com/SaiJd58.png)

**Comment by stephanrauh** [comment]
Maybe we've raised the z-index of the modal to high?

**Comment by TheCoder4eu** [comment]
Yes the z-index could be an explanation, it is hard to say just from the picture, do you have a snippet?

**Comment by bilak** [comment]
This code should be suitable for that. It's not issue of modal only.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui">
<f:view>
    <h:head>
        <title>FILE UPLOAD</title>
    </h:head>
    <h:body>
        <h:form enctype="multipart/form-data">
            <p:fileUpload/>

            <b:commandButton ajax="true" value="modal" onclick="$('.testModalPseudoClass').modal();"/>
        </h:form>
        <b:modal title="testModal" styleClass="testModalPseudoClass">
            <h:form id="testForm">
                <p:fileUpload/>
            </h:form>
        </b:modal>
    </h:body>
</f:view>
</html>
```

**Comment by TheCoder4eu** [comment]
I had time for just a short look:
after selecting a file and clicking on modal, it seems that somehow part of the view is mirrored in the modal.
At first glance it doesn't seem a CSS problem but rather a markup manipulation problem.

**Comment by TheCoder4eu** [comment]
Ok, I admit I am a little confused by your example and what you asked...
1) "If some input or button is under this element, it's not accessible by mouse click. " if you mean you cannon click what is covered by the Modal, well ... it is the purpose of a Modal, otherwise could you please explain in more detail what you mean ?
2) you have a page with a p:fileUpload with a modal with a p:fileUpload
by me, the behaviour in FF and Chrome after loading this page is:
 - I click on the modal button => it lets me choose the file and the file is selected in the first p:fileUpload (if the purpose was opening the modal it fails)
- if I click the modal button after selecting a file, the modal opens and I can select another file.
- I do not see strange interface issues.
what was the desired workflow?

**Comment by bilak** [comment]
Hi, 
sorry for bad description. Try to change code to this:


```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui">
<f:view>
    <h:head>
        <title>FILE UPLOAD</title>
    </h:head>
    <h:body>
        <h:form enctype="multipart/form-data">
            <p:fileUpload/>

            <b:commandButton ajax="true" value="modal" onclick="$('.testModalPseudoClass').modal();"/>
        </h:form>
        <b:modal title="testModal" styleClass="testModalPseudoClass">
            <h:form id="testForm">
                <b:panelGrid colSpans="4,8">
                    <h:outputLabel value="Input:"/>
                    <b:inputText value="Test"/>

                    <h:outputLabel value="Upload:"/>
                    <p:fileUpload/>
                </b:panelGrid>
            </h:form>
        </b:modal>
    </h:body>
</f:view>
</html>
```

then try to access inputtext with mouse click. I can't do that, because upload has overlay over this input and when I click there file dialog is opened.
![image](http://i.imgur.com/mXlBlRu.png)

**Comment by TheCoder4eu** [comment]
Thanks,
I reproduced the problem and understood what is happening.
The problem is that the `<p:fileUpload/>` component specifies a questionable CSS rule:

```css
.ui-fileupload-buttonbar .ui-fileupload-choose input {
    transform: translate(-300px, 0px) scale(4);
}
```

wich "extends"  the clickable area of the Choose button around it, covering other clickable elements of the page.
Disabling this rule, everything works as expected (at least in FF and Chrome), so I don't understand well why this rule has been added.
The solution is to add a padding of at least 20px to the input text, or add an empty row before the upload widget.

**Comment by stephanrauh** [comment]
Now I managed to reproduce the bug, too. It's really a weird CSS rule.

As a workaround, I suggest to add this snippet to your JSF file (or even better, to your *.css files - but in this case you may have to add an !important):
```xml
<head>
        <style> .ui-fileupload-buttonbar .ui-fileupload-choose input { transform:translate(0px, 0) scale(1) }
        </style>
</head>
```

**Comment by stephanrauh** [comment]
I opened a bug on the PrimeFaces bug tracker. See https://github.com/primefaces/primefaces/issues/460.
