### ISSUE TITLE
BootsFaces website showcases not displayed

### ISSUE THREAD

**Issue by Jakasha** [TheCoder4eu/BootsFaces-OSP#1127]
Hi,
since a week the Bootsfaces showcases are not displayed for a lot of components:

https://showcase.bootsfaces.net/forms/commandButton.jsf
https://showcase.bootsfaces.net/layout/basic.jsf
...

Best regards

**Comment by macbl** [comment]
Same here, would be nice if you could fix this. Is there any offline documentation one can use in the meantime?

**Comment by stephanrauh** [comment]
Sure, the showcase is a web application, so you can run it yourself. Just import it as a Maven or Gradle project, whichever you prefer. It's hosted here:

https://github.com/TheCoder4eu/BootsFacesWeb

**Comment by vsvetoslavov** [comment]
No idea why this issue was closed, but it leaves a very very bad impression when the examples not only don't work, but produce a blank page. If you were visiting some library's page, would you use it after you see such thing? Or would you think "Man their own examples don't work, why would I bother..."
The fact that @stephanrauh offered an alternative for devs in need of some doc doesn't fix the issue.
All this is but my own humble opinion, of course. ;)

**Comment by stephanrauh** [comment]
Strange. We've closed the ticket because I've restarted the showcase. It seems to be crashing after a few days. I don't have a clue what's going on. It's not a JSF bug. It looks like files get scrambled after a while. For example, this evening the server delivered half of the HTML code of `/bootstrap/labelsbadge.jsf`.  No idea what happened to the last kilobyte.

**Comment by geopossachs** [comment]
Hallo i have setup an wildfly with a showcase in a container on a other VM from my fork of https://github.com/TheCoder4eu/BootsFacesWeb on

**https://showcase.bootsfaces.pecer.de/**

**Comment by stephanrauh** [comment]
Awesome! Thanks a lot!
