### ISSUE TITLE
New component: Scrollspy

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#113]
No idea whether it's possible or useful to implement it in JSF, but I really like the [scrollspy](http://getbootstrap.com/javascript/#scrollspy). I figure it could be useful in our showcase.

**Comment by exabrial** [comment]
just adding a +1.  Thanks

**Comment by zhedar** [comment]
This is quite old now, but I wanted to add, that there is PrimeFaces Extensions' [Waypoint](http://www.primefaces.org/showcase-ext/views/waypoint.jsf) in the JSF world. However a quick look into that showed that, it uses [Waypoints](https://github.com/imakewebthings/waypoints), so that's probably a similar approach.
Just in case, someone looks this up in need of such a feature.

**Comment by stephanrauh** [comment]
It may be old, but it's far from being forgotten :). I'll have a look at the Waypoint component, and maybe I'll even ask Thomas Andraschko (albeit it's always difficult to ask the competitor for advice without paying something back :)). However, Scrollspy is a standard Bootstrap feature, so chances are we'll simply follow the API suggested by Bootstrap. Nonetheless, thanks a lot!

**Comment by asterd** [comment]
The scrollspy component was implemented using the bootstrap scrollspy feature. In 0.8.2 snapshot there is the implementation and also an example in the showcase.

**Comment by TheCoder4eu** [comment]
@asterd right, it is under bootstrap/ScrollSpy.jsf

So, can we can close this issue?

**Comment by asterd** [comment]
Yep!
