### ISSUE TITLE
Documentation is not reachable

### ISSUE THREAD

**Issue by simartn** [TheCoder4eu/BootsFaces-OSP#1202]
https://showcase.bootsfaces.net/ is not reachable.

Not sure if this is the right place to state this, but I don't know where else I should post about it.

**Comment by stephanrauh** [comment]
@TheCoder4eu I've restarted the server, but it's still unreachable. What's gone wrong?

**Comment by stephanrauh** [comment]
@simonnagl In the meantime, you can use https://showcase.bootsfaces.pecer.de/.

**Comment by simartn** [comment]
Great, thank you for your fast reaction!

**Comment by stephanrauh** [comment]
@TheCoder4eu FYI: the showcase is still down.

**Comment by simartn** [comment]
https://showcase.bootsfaces.pecer.de/ is down too.

**Comment by stephanrauh** [comment]
Maybe it was down, but right now, it's up again.

@geopossachs Do you know something about an outage of your BootsFaces showcase?

**Comment by TheCoder4eu** [comment]
Hi sorry for the late answer, I don't know if this is related but I received strange notifications from the Service Provider.
I am investigating and hope to restore the service soon.

**Comment by TheCoder4eu** [comment]
Solved: unfortunately the dismissal of an unneeded service which was still somehow referenced in the nginx config prevented nginx to restart upon a server restart due to a maintenance of a hardware switch.

Anyway, we already planned to migrate bootsfaces.net and the related websites to a new, modern and more reliable infrastructure, in the next weeks.

Regards,
BootsFaces staff.
