### ISSUE TITLE
Bug: <b:selectOneMenu /> does not trigger <f:ajax /> events

### ISSUE THREAD

**Issue by Pauldic** [TheCoder4eu/BootsFaces-OSP#134]
![selection_554](https://cloud.githubusercontent.com/assets/2055780/8661539/3575ed10-29b0-11e5-931d-d9c132c106bd.png)

And this makes it impossible to have a chained b:selectOneMenu

**Comment by stephanrauh** [comment]
Same applies to ```<b:inputText />```, ```<b:checkbox />```, ```<b:datePicker />``` and ```<b:slider />```.

**Comment by stephanrauh** [comment]
Also see https://github.com/TheCoder4eu/BootsFacesWeb/issues/5.

**Comment by stephanrauh** [comment]
@mweiland reports:

When trying to update value of an input field with f:ajax i found

``` xml
<h:panelGrid columns="2">
             <h:outputText value="ID: "/>
             <b:inputText styleClass="tx-input-hours" id="inputID" value="#{testBean.id}" >
                <f:ajax event="keyup" render="inputName" execute="@this" />
           </b:inputText>
             <h:outputText value="Name: "/>
            <b:inputText styleClass="tx-input-hours" span="4" id="inputName" value="#{testBean.name}"/>
</h:panelGrid>
```

does not work, when you replace b:input text with h:input text, it works.

mojarra 2.2.11
bootsfaces 0.7.0

**Comment by AlexanderBl4h** [comment]
I can confirm this bug very well, found it, too.

**Comment by stephanrauh** [comment]
I don't like the f:ajax facet. How do you like this approach?
http://www.beyondjava.net/blog/an-alternative-api-to-jsf-ajax/

**Comment by AlexanderBl4h** [comment]
:+1: I do like this!

**Comment by stephanrauh** [comment]
@AlexanderBl4h You mentioned a typo in your comment on my blog, but it seems to have gone lost in the editor, so I don't know which typo you talk about. Would you mind to tell me again?

**Comment by AlexanderBl4h** [comment]
<h:form>
	   <h:inputText value="#{helloBean.name}" />
	   <h:commandButton value="Welcome Me"
						process="@previous" update="@next" >
	   <h:outputText value="#{helloBean.sayWelcome}" />
	</h:form>

You don't mean `<p:commandButton>`?

**Comment by stephanrauh** [comment]
@AlexanderBl4h You've got sharp eyes. Thank, I've fixed the typo! 
(I'm still hoping someone writes a debugger for Wordpress articles...)

**Comment by AlexanderBl4h** [comment]
I never worked with wordpress. But there are other blog-frameworks so far. I am using Jekyll for my personal webpage. (In progress!).

**Comment by stephanrauh** [comment]
Started to work on the AJAX topic.

**Comment by AlexanderBl4h** [comment]
FYI: `<b:selectBooleanCheckbox` is also affected by this one. I am forced to use the JSF one here. :-1:

**Comment by stephanrauh** [comment]
I've implemented the new unified AJAX API for five components so far:
* b:commandButton
* b:inputText
* b:selectBooleanCheckbox
* b:selectOneMenu
* b:

To dos left:
* Implement the JSF-style f:ajax API, such as 
```xml
<b:commandButton value="f:event"                                                             
	actionListener="#{imageGallery.chooseAnotherImage(image)}"                               
	action="#{AJAXBean.standardJSFAction}">                                                  
	 <f:ajax listener="#{AJAXBean.standardJSFActionListener}" update=":messages"></f:ajax>   
</b:commandButton>                                                                           
```

**Comment by Pauldic** [comment]
Awesome!!!

**Comment by stephanrauh** [comment]
Current state of the art: We've implemented the new unified AJAX API for eight components so far:
* b:image (¡gracias! a Yeray)
* b:carousel (untested)
* b:commandButton
* b:inputText
* b:selectBooleanCheckbox
* b:selectOneMenu
* b:icon
* b:iconAwesome

There's also a demo using the drag'n'dop JavaScript events to call Java methods via AJAX (www.angularfaces.net/BootsFacesChess-1.0.0-SNAPSHOT/). 

We've also implemented the JSF-style f:ajax API (but postponed to implement prime:ajax due to classpath issues). E.g.
```xml
<b:commandButton value="f:event"                                                             
	actionListener="#{imageGallery.chooseAnotherImage(image)}"                               
	action="#{AJAXBean.standardJSFAction}">                                                  
	 <f:ajax listener="#{AJAXBean.standardJSFActionListener}" update=":messages"></f:ajax>   
</b:commandButton>                                                                           
```

To dos left:
* implement redirection on actions
* test b:carousel
* start more systematic testing :)
* add AJAX and JavaScript events for swipe events
* implement AJAX for jQuery event (such as carousel onslide/onslide and the panel expand/collapse actions)

**Comment by stephanrauh** [comment]
Finished implementing and documenting the new AJAX API.

**Comment by farooq7124** [comment]
Hi ,

Is there any AJAX api for <b:dataTable /> as we have for primefaces as <p:ajax event="page"
							oncomplete="userDetailTableWidget.clearSelection();" />

**Comment by stephanrauh** [comment]
What precisely do you ask for? Do you want us to add a `page`event? Or do you want us to add an `oncomplete` listener?

BTW, this is a closed issue - we only see your question because GitHub eagerly sends mails, but we don't see it when working with the bug tracker.

**Comment by farooq7124** [comment]
Hi Stephan,

Thanks for swift reply. Yes events like Page, RowEdit. Please help me with this.

Thanks,

**Comment by stephanrauh** [comment]
I'm not sure we can do this, because `b:dataTable` is rendered on the client. So many events can't be caught by the Java bean, simply because they are processed on the client. That's a deliberate design decision. To react to datatable issues, you have to use JavaScript.

But still, your proposal sounds interesting. We should investigate the topic further. Why don't you open a new issue so we can track it more easily?
