### ISSUE TITLE
Missing attributes in `<b:datepicker`

### ISSUE THREAD

**Issue by AlexanderBl4h** [TheCoder4eu/BootsFaces-OSP#144]
According to the PrimeFaces `<p:calendar>` (http://www.primefaces.org/showcase/ui/input/calendar.xhtml) there are in my opinion some missing attributes in the BootsFaces `<b:datepicker>`:
- required: always usefull (I mean, why not?)  and message.
- min/max date
- pattern 
- disabled

Also the time is missing. Maybe it is better to use a calendar instead of a datepicker and create an attribute like `time` which can set to `false` or `true` (true default) to display/use the time.

**Comment by stephanrauh** [comment]
As for the time picker: this one might be nice: http://www.daterangepicker.com/. It also covers date and time ranges.

**Comment by AlexanderBl4h** [comment]
:+1:

**Comment by stephanrauh** [comment]
The datetimepicker seems to be popular - see #148. We should also think about supporting the Joda date time library and the new date / time classes of Java 8.

**Comment by anemdhana** [comment]
Thanks and using datetimepicker than daterangepicker ? See if you think these converter classes are useful to the project. https://gist.github.com/anemdhana/403c0923c1e25ff289fe

**Comment by stephanrauh** [comment]
@anemdhana Yes, your classes look useful. Thanks!

**Comment by stephanrauh** [comment]
As it turns out, `disabled`, `min`, `max` and `pattern` are already there. We just forgot to document them and to add them to the taglib (i.e. to your editors autocomplete list).

**Comment by AlexanderBl4h** [comment]
How does the pattern work? I can not figured it out. :( Can you please provide some examples?

**Comment by zhedar** [comment]
@AlexanderBl4h You can supply a pattern by setting the `dateFormat` attribute. However, while testing this I found, that it only works, if `lang` is set as well. I probably have a closer look at that, because it seems redundant. The pattern itself uses the [SimpleDateFormat patterns](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html).
A rather exotic example may be:

    <b:datepicker lang="it"  dateFormat="dd,MM"/>

I noticed, that setting the lang code to `en` won't apply the supplied  `dateFormat`. Other codes like `de`, `it`, `es` seem to work though. That's definitely something we still need to work on.

**Comment by stephanrauh** [comment]
@zhedar I've assigned the ticket to you, because you seem to have started investigating it.

**Comment by zhedar** [comment]
@stephanrauh If I find the time this week, is this something we won't to include in 0.8.2? Part of it seems easy enough to fix.

**Comment by stephanrauh** [comment]
Sure. If it's a low-hanging fruit, we should pick it.

**Comment by zhedar** [comment]
Seems like I have just fixed the bug we had: If a `lang` was given, were we had a region available, regional settings overwrote custom ones, therefore the `dateFormat` was resetted to be the regional one. That's why you needed to provide an illegal `lang` code, since the request locale is used as the default one if you don't set any. In my case, that defaulted to `de` and caused problems.

Probably will look into implementing those missing attributes tomorrow, it's getting late 👎

**Comment by stephanrauh** [comment]
I guess most of the requested features already have been implemented (either in b:datePicker, or b:dateTimePicker, or both), but let's move this to the next version in order to be able to test thoroughly.

**Comment by jottyfan** [comment]
Why do you not use https://github.com/xdan/datetimepicker instead? For me, this is much easier to choose times for a schedule that has a slot time of 15 minutes. Just 2 mouse clicks to select the date with time, no scrollbars to fiddle around with, no seperate pages for calendar and time, etc. Or would it be better to create a new component as an alternative for the current implementation?

**Comment by stephanrauh** [comment]
@jottyfan Did you already discover the new DateTimePicker of BootsFaces? Or do you suggest an alternative to `<b:dateTimePicker />`?
http://showcase.bootsfaces.net/forms/DateTimePicker.jsf

**Comment by jottyfan** [comment]
yes, I've had a look at http://showcase.bootsfaces.net/forms/DateTimePicker.jsf - but I think https://github.com/xdan/datetimepicker is a better solution in special cases that I know, where you do not stick to a minute exactly but to interval times, for exampel to quarters. For me it's easier to use xdan's extension, therefore, I think this could be an alternative implementation of bootsfaces datetimepicker. I wonder if this should be part of the current dateTimePicker component (to switch the underlying javascript implementation by an attribute) or if it is better to create a new component...

**Comment by stephanrauh** [comment]
I see. Using a switch might be difficult. Most likely the widgets are similar, but not similar enough. Defining just another component is difficult, too. You might end up with zillions of components.

**Comment by stephanrauh** [comment]
Back to the original topic. This is the state of the art:

`<b:datePicker>`:
- [x] required and requiredMessage.
- [ ] min/max date
- [ ] pattern
- [ ] disabled

`<b:dateTimePicker>`:
- [ ] required and equireMessage.
- [ ] min/max date
- [ ] pattern
- [ ] disabled

**Comment by stephanrauh** [comment]
Some time ago, we've decided to deprecate the good old `<b:datePicker>` in favor of `<b:dateTimePicker>`. The rationale being that we'd like to get rid of jQueryUI, and `<b:datePicker>` is one of the two components requiring jQueryUI. Since the new component `<b:dateTimePicker>` supports the required features, I've decided to close the ticket.
