### ISSUE TITLE
No Tooltip displayed with Spring Boot JSF in Embedded Tomcat

### ISSUE THREAD

**Issue by oakdalesoft** [TheCoder4eu/BootsFaces-OSP#199]
The text of the tooltip appears but not its container graphic. Also pushes subsequent elements downwards on activation.

**Comment by stephanrauh** [comment]
I know at least one BootsFace application displaying tooltip correctly:
![image](https://cloud.githubusercontent.com/assets/3045767/10866404/23f1b672-802d-11e5-8fc6-447a4f45cc0b.png)

So would you mind to give us more context information? What is your program doing, how is it configured, and how does the broken tooltip look like? If possible, add the source code so we can reproduce the problem.

**Comment by oakdalesoft** [comment]
Give me a little time and I'll upload a Spring Boot project that has the problem to GitHub.

**Comment by stephanrauh** [comment]
Ah, I see. Spring Boot doesn't initialize JSF correctly, so you're likely to run into all kind of problems. It's definitely broken with Mojarra 2.2.11+. Chances are you get it up and running with Apache MyFaces. In any case, the development team at Oracles' doesn't support Spring Boot, so it's difficult to fix it on our side. Nonetheless, I'm looking forward to seeing your project.

**Comment by oakdalesoft** [comment]
Hi,

I've posted an example project to: https://github.com/oakdalesoft/tooltip-issue

I look forward to discovering what I'm doing wrong because all my boot applications are doing this when I try and add bootsfaces.

Thanks.

![issue](https://cloud.githubusercontent.com/assets/2308099/10903906/9b60f58a-8206-11e5-8b26-466d09d10168.PNG)

**Comment by stephanrauh** [comment]
Whatever the reason may be - we seem to have fixed it in BootsFaces 0.8.0. Please try the snapshot version (as described in #151) and report us back. Thanks!

By the way, it's a nice demo! Plus, it's good to see Apache MyFaces is still compatible to Spring Boot. I decided to deny support of Spring Boot because of the incompatibility to Mojarra 2.1.12+, but I never liked this decision.

![image](https://cloud.githubusercontent.com/assets/3045767/10923884/a40858e0-8283-11e5-93d7-3f90563e5903.png)
