### ISSUE TITLE
RTL direction

### ISSUE THREAD

**Issue by mostfa-ayad** [TheCoder4eu/BootsFaces-OSP#228]
hi 
it's good work
how can i use  it in full rtl support

**Comment by stephanrauh** [comment]
Well, you're the expert, no me :). I need your help to get RTL support up and running because I can't read any RTL language. But I believe it's pretty simple:
* First, fetch BootsFaces 0.8.1 first. For some reason, we always had the RTL attributes, but a couple of days ago I noticed there's no implementation. 0.8.1 fixes this. Currently, it's only a developer preview, not a finished release. So read issue #151 on how to get it.
* add the bootstrap-rtl.css from https://github.com/morteza/bootstrap-rtl 
* add the attribute `dir="RTL"` to your HTML tag:
```xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      dir="rtl">
```
Please report back if this works for you.

**Comment by stephanrauh** [comment]
I've uploaded a new developer snapshot and documented RTL support at http://bootsfaces.net/Staging/layout/rtl.jsf.

**Comment by mostfa-ayad** [comment]
good work    i need version  0.8.1 to try it

**Comment by stephanrauh** [comment]
@mostfa-ayad Did you get it up and running? Strictly speaking, you don't need BootsFaces 0.8.1. It just adds more options. But basically all you need to add to your project (and to your JSF views) is the https://github.com/morteza/bootstrap-rtl css file.

**Comment by mostfa-ayad** [comment]
you are  right  i try it  and it  work  fine  thank you  i test it in navbar and sidebar and work good

**Comment by stephanrauh** [comment]
That's great news, thanks!

**Comment by stephanrauh** [comment]
Also see #216 and #99.
