### ISSUE TITLE
Drop support for IE 8 and previous versions

### ISSUE THREAD

**Issue by TheCoder4eu** [TheCoder4eu/BootsFaces-OSP#231]
The IE8/9/10 versions will be EOL by 12 January 2016:
https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support
https://support.microsoft.com/en-us/kb/3123303?sd=rss&spid=14019

jQuery 2.x has the same API as jQuery 1.x, but does not support Internet Explorer 6, 7, or 8.
In addition, Internet Explorer 8 requires the use of Respond.js to enable media query support.

IE8 had a global 1,87 % share in December 2015.

I think the time has come to use jQuery 2.x instead of jQuery 1.x, plus Respond.js and other JS supporting old browsers.

**Comment by TheCoder4eu** [comment]
Another one that we could get rid of is html5shiv.js, that enables use of HTML5 sectioning elements in legacy Internet Explorer and provides basic HTML5 styling for Internet Explorer 6-9, Safari 4.x (and iPhone 3.x), and Firefox 3.x.

**Comment by stephanrauh** [comment]
I'm always in for getting rid of IE8 support. But what about companies? Do you have any statistics which browsers are used in the corporate world?

**Comment by asterd** [comment]
as you can see here: https://www.w3counter.com/trends (and in many other sites), the usage of ie8 is rapidly collapsing. What i see here, in Italy, is that almost all have upgraded the browser, even if they are still on windows Xp. 
So, apart from rare case, there is at least an ie9. So i think is time to drop IE8 support!

**Comment by TheCoder4eu** [comment]
Let's decide it after 0.9.0

**Comment by TheCoder4eu** [comment]
On June 9, 2016 , jQuery 3.0 has been released :
"jQuery 3.0 will become the only version of jQuery. The 1.12 and 2.2 branches will continue to receive critical support patches for a while, but will not get any new features or major revisions. Note that jQuery 3.0 will not support IE6-8. If you need IE6-8 support, you can continue to use the latest 1.12 release."

So we could keep for a while a flavor with 1.12 and one with 3.x .

**Comment by TheCoder4eu** [comment]
Should we drop IE8 support or wait a future release?
Please vote

**Comment by asterd** [comment]
To me we can drop ie8 support from this release. It is already out of
microsoft support and a lot of frameworks drop support to it..

Il 09 ott 2016 20:07, "TheCoder4eu" <notifications@github.com> ha scritto:

Should we drop IE8 support or wait a future release?
Please vote

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/TheCoder4eu/BootsFaces-OSP/issues/231#issuecomment-252502115>,
or mute the thread

**Comment by stephanrauh** [comment]
According to Statcounter, we can safely drop IE8 support. However, we should also check the statistics of our showcase, because companies tend to be more reluctant to update their browser than the average user.

![image](https://cloud.githubusercontent.com/assets/3045767/19223182/e19e03d8-8e69-11e6-87f8-aab44647cbf6.png)

**Comment by TheCoder4eu** [comment]
Bootstrap 4 dropped support for IE8, see
http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

> Dropped IE8 support . Dropping support for IE8 means we can take advantage of the best parts of CSS without being held back with CSS hacks or fallbacks.

**Comment by TheCoder4eu** [comment]
From the current Bootstrap v4 Migration guide:

> Browser support
> 
>     Dropped IE8, IE9, and iOS 6 support. v4 is now only IE10+ and iOS 7+. For sites needing either of those, use v3.

**Comment by TheCoder4eu** [comment]
BootsFaces v1.x will continue support legacy browsers.
BootsFaces v2.x will be Bootstrap v4 and will support Modern Browsers only.
