### ISSUE TITLE
responsive datatable

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#233]
Dear Contributors,

I would like to ask you, please put the datatable body into `< div class="table-responsive" >..< div >` wrapper.

Thank you,
Lyahim

**Comment by stephanrauh** [comment]
I can put the entire datatable into such a wrapper. Is that what you suggest?

I'm using this component: https://www.datatables.net/manual/styling/bootstrap. It's a finished component, so I'm afraid its difficult to modify the HTML code of the datatable itself.

**Comment by lyahim** [comment]
Hello Stephanrauh!

I think enough put only the jsf generated part put into the wrapper. Because that part could be wider that screen.

At now I put the whole table into the wrapper, but when I scroll to right, the search block disappeared after a time.

< div class="table-responsive" >
		<b:dataTable ...>

I think it is not the best behaviour, what do you think?

**Comment by stephanrauh** [comment]
Honestly, I don't have the slightest idea :). That's why I declared b:datatable "experimental" in BF 0.8.x. I've added the wrapper div in BF 0.9.0 and uploaded a developer snapshot to Maven Central. Please read #151 on how to get the snapshot version and give it a test. My own demo works fine with the wrapper class, but I'd appreciate your feedback, too.

Thanks in advance!
Stephan

**Comment by lyahim** [comment]
Ok Stephan, I will try it. Just at now I haven't enough time. But I have a plan to make some pull request in future :)

**Comment by stephanrauh** [comment]
@lyahim Take your time. There's no hurry. There's even a faint possibility that we decide to use another Bootstrap datatable. I don't believe it, because I did some investigation before choosing the datatable of www.datatables.net, but I can't say for sure that this datatable is flexible enough to meet the requirements of JSF.

BTW: I intend to add all those attributes and configuration option to the b:dataTable in the next couple of weeks, so maybe you should have a look at the 0.9.0-branch when you start with your pull request.

**Comment by stephanrauh** [comment]
I'll close this bug because I've implemented the addition you requested. Currently, there's nothing left to do. But I'll still watch this ticket. Feel free to comment here if you've found out something new about our responsive datatable.
