### ISSUE TITLE
dataTable optional wrapper

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#242]
Hello All,

Is it possible to expand the dataTable attributes what enable to generate a simple table?

Best Regards,
Mihaly

**Comment by stephanrauh** [comment]
I don't understand your question. Do you want a simple HTML table, without sorting and without paginator?

**Comment by lyahim** [comment]
Yes, I think that.
I know it simply to use instead h:dataTable with styles, but if I want a normal responsive table, need to add a div too. And in future may be better if you have a basic table with full source code control.

It is only an opinion, and I know there isn't the most urgent request. :)

**Comment by stephanrauh** [comment]
I'm reluctant to write a datatable because there's no way we can ever beat the PrimeFaces datatable. My standard recommendation is to use their datatable. I only started to work on the client-side datatable because that's something PrimeFaces doesn't offer yet, so we can generate some extra value.

So, yes, writing a datatable that's generated on the server may be useful, but let me postpone it to a future version. Datatable are a lot of work to implement.

**Comment by stephanrauh** [comment]
I suppose our `<b:dataTable >` is what @lyahim wanted to see. And probably a lot more.
