### ISSUE TITLE
@previous doesn't work if it's in a b:column

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#256]
This code doesn't work. That's obvious, but it seems to result in a endless loop.
```xml
<b:column>
   <b:message for='@previous' />
</b:column>
```

**Comment by zhedar** [comment]
This doesn't seem to be limited to columns. I suspect it's related to `NamingContainers`, because it also fails inside a `b:panel`, if there is no content before the `b:message`. 
For example

    <h:form id="form1">
        <b:panel title="test" look="primary" id="panel1" collapsible="false">
	     <b:message for='@previous' />
	     <b:inputText value="test"/>
        </b:panel>
     </h:form>
fails in exactly the same way.

When I read the purpose of `@previous` it seemed quite clear:
> @previous finds the previous JSF element in the same level of the JSF tree.
If there is nothing in front of `@previous`, it will get sad and search forever :(. We may need to introduce a check for that OR let it use its parent component, if it is the first child component.
