### ISSUE TITLE
Page reload question

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#274]
Hello All,

I'm not sure for this topic is bug or not, therefore I make a question. :)
The situation is the following: I have a commandButton(I tried both native JSF and Bootsfaces) with a simple action(called delete). In backing bean I have an operation for delete something.
After I click the button that refresh the whole page, what is the correct behaviour, because it isn't ajaxable. But after that in browser I push the F5 button I get the message 'would like to reload the page with same request' or something similar(I have Hungarian locale).
What I tested:
1) I tried both native JSF and Bootsfaces
2) public String delete() with return "";
3) public String delete() with return null;
4) public void delete()

In all case I get the same behaviour. My question is: Is it the correct behavour, or I do something wrong, or It is a bug?

Thank you,
Mihaly

**Comment by XaeroDegreaz** [comment]
That's because by default the button is performing a `POST` request. When you attempt to refresh any form (on any site) that has been submitted via `POST` your browser warns you that if you refresh the page, your request will try to submit again.

[This post](http://stackoverflow.com/questions/13070537/difference-between-hbutton-and-hcommandbutton) has an excellent breakdown about how `commandButtons` work.

In order to get the behaviour you're wanting, you may want to use a `commandLink` instead.

**Comment by stephanrauh** [comment]
This might be a valid usecase for the POST-GET paradigm. Sometimes developers add the parameter `?faces-redirect=true` to make sure that the user can use the F5 button without deleting a second row.

**Comment by stephanrauh** [comment]
I'll close this ticket because I don't think it's a bug. Feel free to continue the discussion - I keep watching this ticket.
