### ISSUE TITLE
new component b:search

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#362]
What about adding `<b:search />`? By default, this component scans every XHTML file to build a search index. Of course, not every attribute should be taken into account. This component might be useful to add a search functionality to our showcase.

The component should also offer callback functions. The idea being that users can index arbitrary content, including their database.

**Comment by zhedar** [comment]
I'm not sure, how this should behave for apps with complex dynamic content. It seems like a rather exotic usecase.

However, we could implements something [Autocomplete](http://www.primefaces.org/showcase/ui/input/autoComplete.xhtml), which would deliver the search bar functionality. It could call backing bean methods as you type to get the results and populate a suggestions menu. Otherwise you could simply rely on a backing collection with a list of objects and use simple lookups to find matches.

We could then implement the indexing of the content in another way and maybe provide an example for that? I think you may want to use fulltext search engines for such a use case.

**Comment by stephanrauh** [comment]
* b:autocomplete sounds good. We could build a small search engine using a clever back-end bean.
* If the use case is too exotic, we could think about creating a second library ("BootsFaces extensions").
* I don't know how difficult it is to set up a full-text search engine, but it might be an alternative, too. Or we can combine both.

**Comment by asterd** [comment]
@stephanrauh @zhedar the autocomplete component is already available both in primefaces and butterfaces. If we want to implement it, we need to do something more. 
The idea to create a BootsFaces extension project seems to be good, just to insert a set of "exotic" component that is not good to insert in the main project.

About full-text search engine, i think that is very difficult to implement, because there are a lot of possibile data sources that may have data not always available in a simple way (think about a dynamic webpage based on current user, complex db schema, results of webservices call, etc..) 

A first step can be the integration of an already available indexer (like lucene) and provide an interface for it, but in this way, i think we can fall in a very shady hole. An indexer require a lot of work to configure, and bootsfaces must be simple ;) 

Otherwise we can think about a client side search engine like 
http://www.tipue.com/search/
http://lunrjs.com/

that can be useful but very simple to implement.
What do you think about that??

**Comment by stephanrauh** [comment]
Cool! I hoped we could find something like a simple jQuery plugin. On first sight, lunrjs or tipue look promising.

**Comment by stephanrauh** [comment]
After running out of team members, it's unlikely we'll ever find the time required to implement this. Let's close the ticket.
