### ISSUE TITLE
accordion: make child panel's title bar clickable?

### ISSUE THREAD

**Issue by jpiersanti** [TheCoder4eu/BootsFaces-OSP#372]
Hello guys,

Thanks a lot for the 0.8.5 version, it provides much more possibilities! 

I have one quick question, is not an issue. While using the accordion component I have noticed that only the text in the title is clickable (as a link) in order to expand/collapse the panels.

Is there a way to make the entire title area (not only the text, but the title bar itself) clickable so the user  can click anywhere on the title area?

Regards,

**Comment by zhedar** [comment]
This is something I experienced as well, it not only holds true for the accordion, it's an issue with all collapsible panels. The title text is an `<a>` which triggers the collapse.
We should find a way to make the whole title bar trigger the collapse, because that's what a user would normally expects and is much more mobile-friendly.

**Comment by zhedar** [comment]
I should have looked into this a bit further, it was too simple to solve. I'm checking, if I have overseen any corner cases before checking in a fix.
