### ISSUE TITLE
Is it possible to overwrite core.css?

### ISSUE THREAD

**Issue by m1rc0** [TheCoder4eu/BootsFaces-OSP#415]
Hi,

I started with the example from https://github.com/TheCoder4eu/BootsFaces-examples/blob/master/src/main/webapp/dashboard.xhtml and put the css in an extra file, which I load with:

        <f:facet name="last">
            <h:outputStylesheet library="css" name="my.css" />
        </f:facet>

I also tried in h:head:

      <h:outputStylesheet library="css" name="my.css" position="last"/>

But for the sidebar the position attribute is always overwritten due to core.css being loaded after my.css. Am I doing something wrong?

Thank you very very much

**Comment by zhedar** [comment]
This is because of a bug in the current version I should have already fixed, see #390.

It will be fixed in the upcoming version, meanwhile you could try to build the library yourself or try a Snapshot release (although it doesn't look like @stephanrauh pushed a current version, have a look at #369 for more information).

**Comment by stephanrauh** [comment]
After reading this, I've just pushed another snapshot of BootsFaces 0.9.0-SNAPSHOT to Maven Central.
