### ISSUE TITLE
Create a <b:footer> that displays its content regardless of whether it's inside an <h:form>

### ISSUE THREAD

**Issue by Robblle** [TheCoder4eu/BootsFaces-OSP#417]
If you have an `<h:form>` around  a `<f:facet type="footer"/>` inside a `<b:modal>` all the footer's contents are not being displayed.

```xml
<b:modal id="modal" title="Test" styleClass="testModal"
                     closable="false" close-on-escape="false" backdrop="true">
    <h:form>
          <f:facet name="footer">
                  <b:button value="Close" dismiss="modal" onclick="return false;"/>
          </f:facet>
    </h:form>
</b:modal>`
```

**Comment by TheCoder4eu** [comment]
Hi @Robblle , Thank you for opening this issue.
Well, since you provided a complete example I can now answer you without doubts:

you are trying to use the b:modal "footer" facet in a h:form, but here is no such facet defined for h:form, so it doesn't know how to handle it and it does not renders its contents.

This is by JSF design: you can't use a facet of a component in a nested component.

**Comment by stephanrauh** [comment]
@Robblle Is there any reason why you want to put the footer in a form?

**Comment by Robblle** [comment]
I wanted to have a save and cancel button inside a modals footer

**Comment by zhedar** [comment]
@Robblle You don't have to put that button into an own form. Just use an enclosing one and limit set button's scope (out of the top of my head, I would recommend setting `process="@this"` or `immediate="true"`).

**Comment by stephanrauh** [comment]
Both `process="@this"` and `immediate="true"` are fine for the cancel button, but nor for the save button :).

**Comment by stephanrauh** [comment]
BTW, sounds like a valid use case to me. As a workaround, you can put the entire model into a form as @zhedar suggested.

**Comment by zhedar** [comment]
@stephanrauh Oops, I've really thought about the cancel button here, because that's the only challenge in this scenario. The save button should include the whole form anyway.

**Comment by stephanrauh** [comment]
Well, but that was the problem. I suppose @Robblle created a form within the modal, and then tried to add the buttons in the footer. You can put the footer in the form because BootsFaces doesn't detect it there. You can't put a `b:commandButton` outside a form because JSF doesn't allow that. So you end up defining a footer consisting of a form containing two buttons. Now the "Save" button submit precisely this form. It doesn't know it's intended to send the input field above the header because that's another form.

So I'm currently pondering whether we should teach BootsFaces to look for the header in the form, too.

**Comment by michbeck100** [comment]
Was there any work on this issue? I stumbled upon the same problem and i think its a common use case to have a `b:commandbutton` as save button.

**Comment by stephanrauh** [comment]
Just put it the other way round, and everything works:

```xml
<b:modal id="modal" title="Test" styleClass="testModal"
                     closable="false" close-on-escape="false" backdrop="
     <f:facet name="footer">
         <h:form>
                  <b:button value="Close" dismiss="modal" onclick="return false;"/>
          </h:form>
     </f:facet>
</b:modal>`
```

**Comment by michbeck100** [comment]
I'm using a b:commandbutton and i would like to process every inputs with "@form". This won't work this way. I can still process another, i know, but i think this is a little bit confusing.

**Comment by stephanrauh** [comment]
I suppose you can solve the issue using one of the BootsFaces search expressions. Let's close this ticket.
