### ISSUE TITLE
unit tests for custom components

### ISSUE THREAD

**Issue by jottyfan** [TheCoder4eu/BootsFaces-OSP#432]
Finding a bug and discussing a feature request lately, I wonder why there are no unit tests on the custom component render classes. This may seem to be a ridiculous overhead for people, but bugs that extend renderers would be detected easier (even #426 would not have come up). I'd like to help in developing such test methods if you use junit for that - but this is a big decision for one of you master maintainers.

Is there any interest in that where I can help making bootsfaces developement better?

**Comment by stephanrauh** [comment]
We're still (and desperately) looking for an efficient way to do automated testing. The overhead of unit tests was so big that we've decided to move the tests into a dedicated project because the tests started to introduce errors in the core libraries (because they add zillions of dependencies that are easily imported, breaking the build later). However, this doesn't seem to work, either.

Also see https://github.com/TheCoder4eu/BootsFaces-Tests

**Comment by jottyfan** [comment]
This is what I was looking for, thanks!

**Comment by stephanrauh** [comment]
I've copied some files from my local BootsFacesWeb project to https://github.com/TheCoder4eu/BootsFaces-Tests/tree/master/BootsFacesWeb. I guess running the tests from a web application makes many things easier because the infrastructure is already there. I'm looking forward to your feedback!

To run the example, check out the BootsFacesWeb project and copy the files into it. It's a couple of week since I last tried, but I hope the code still works.
