### ISSUE TITLE
Possibility to make columns not searchable in b:dataTableColumn

### ISSUE THREAD

**Issue by susanne69** [TheCoder4eu/BootsFaces-OSP#435]
Hi Stephan, Philipp,

It's me again. How about a possibility  to say searchable= somthing like you do orderable = something for b:dataTableColumn?

Kind regards,
Susanne

**Comment by stephanrauh** [comment]
Definitely a good idea. Maybe we can schedule it in 0.9.1.

CU
Stephan

**Comment by stephanrauh** [comment]
Done, tested and documented. See http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf or test yourself using the new developer snapshot I've published a moment ago.

**Comment by susanne69** [comment]
I got now bundle date 20160630-15:40:06.
searchable does not seem to be an attribute of b:dataTableColumn. If I set it anyway then nothing changes. How do I use the new attribute?

**Comment by stephanrauh** [comment]
Oh, you're right - instead of adding `searchable` to `b:dataTableColumn` I added `sortable`. Which is nice, but is a synonym of `orderable`. I fixed that.

As for the functionality: have a look at the second demo at http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf. If both `searching="true"`and `multi-column-search="true"`, `searchable="true"` should make a difference.
