### ISSUE TITLE
Add bootstrap-select support to BootsFaces

### ISSUE THREAD

**Issue by cooper-lyt** [TheCoder4eu/BootsFaces-OSP#446]
in my old project I use [bootstrap-select](https://silviomoreto.github.io/bootstrap-select/), it is Good!

do you have plan add [bootstrap-select](https://silviomoreto.github.io/bootstrap-select/) to BootsFaces?

 If I work on this now , Are you accept my pull requests?

I want create a component `selectMenu` for bootstrap-select, This component has conflicts with the `b:selectOneMenu` and `b:selectMany`.

or I create other project， depends on the bootsFaces?

**Comment by stephanrauh** [comment]
I believe your `b:selectMenu` component should be an extension of `b:selectOneMenu`. Which is to say: it should support the same attributes. Shouldn't be a problem, from what I saw at their website. If you manage that: go ahead!

Do you already know about our XText plugin? It generates a lot of the code and even of the documentation of your components. The bad news it that it runs only on Eclipse. In any case - have a look at our **/BootsFaces.jsfdsl file, add your component and it's attributes there. I believe you'll cope. If not, don't hesitate to ask us.

Thanks in advance
Stephan

**Comment by cooper-lyt** [comment]
ok , i try  XText plugin!

**Comment by stephanrauh** [comment]
Have a look at https://github.com/stephanrauh/JSFLibraryGenerator/tree/master/plugins. You find the current version of the plugin and a short installation instruction. Hope that helps!

**Comment by TheCoder4eu** [comment]
Hi,
I am moving this issue on v1.1;
- I don't see any `b:selectMenu` component implementation yet
- the selectOneMenu already have a bootstrap-select look and feel (thanks to the form-control CSS class)

The interesting features of bootstrap-select are already delivered from the

Bootstrap Multiselect - http://davidstutz.github.io/bootstrap-multiselect/ 

plugin, used to implement the `b:selectMultiMenu` component.

We can discuss if bootstrap-select would better fit the implemented functions and has a better look and feel.
I would be personally favorable to consider switching from bootstrap-multiselect to bootstrap-select if it covers all the features we need, also because it is also used by PatternFly.

@asterd , @stephanrauh @zhedar , what do you think?

**Comment by stephanrauh** [comment]
Patternfly is a good reason to migrate to another component. We should consider this.

**Comment by stephanrauh** [comment]
Currently, we've got the select2 widget, which is also very good. I believe we can close this ticket.
