### ISSUE TITLE
Panel open position not stored when Hibernate Validation fails

### ISSUE THREAD

**Issue by Coolius70** [TheCoder4eu/BootsFaces-OSP#464]
```xml
			<b:accordion expanded-panels="conditions">
				<b:panel id="conditions" title="Matching Kriterien" look="primary" >
					<h:form id="formSaveConditions">
						<b:row>
				...
				</b:panel>
				<b:panel id="personalien" title="Personalien" look="primary">
					<h:form id="formSavePersonalien">
				...
						</b:row>
					</h:form>
				</b:panel>
				<b:panel id="contactData" title="Kontaktdaten" look="primary">
					<h:form id="FormSaveContactData">
				...
					<b:row>
							<b:column col-md="2" style="line-height:250%">
								<h:outputText value="Weitere" style="font-weight:bold" />
							</b:column>
							<b:column col-md="4">
								<b:inputText value="#{freelancerBean.other}"  id="other" />
							</b:column>
							<b:column col-md="6">
								<b:message for="other" span="4"></b:message>
							</b:column>
						</b:row>
						<b:row>
							<b:column col-md="2" />
							<b:column col-md="4">
								<b:commandButton id="saveContactData" value="Speichern" look="primary" action="#{freelancerBean.saveContactData}" />
							</b:column>
							<b:column col-md="3">
								<b:message for="saveContactData"></b:message>
							</b:column>
						</b:row>
					</h:form>
				</b:panel>
			</b:accordion>
````

when validation with hibernate validators fails, it seems that the page is reloaded and the panel is opend with the panel which is indicated in the xhtml page, e.g. b:message for="other" is shown. In case that validation is fine it works (e.g. b:message for="savedContactData")

**Comment by stephanrauh** [comment]
I didn't find enough spare time to reproduce the issue, but from what I remember from the preceding emails reproducing the issue goes as follows:
- implement a custom JSR303 validator
- use this annotation to validate on the of input fields
- click on a `b:commandButton`.

If the validation fails, the page is reloaded.

Todo:
- Check if the page reload also happens on AJAXified commandButton. If so, this issue is clearly a bug.
- Check if the page reload is the desired behavior on non-AJAX commandButtons.
- If it is, let's check if there's a way to store the state of b:panel, b:accordion and b:modal. The idea being that a modal dialog shouldn't be closed automatically after trying to save the input just because the input is invalid.

**Comment by Coolius70** [comment]
It happens on any validation. My prior mail was based on a typo on the field I checked. Morover it happens also on OK message which are rendered from the server, but with my workaround to store serverside the open panel I was misinterpreting this.

By adding update="{id form the button is in}" the panel remains open which solves the problem. If the update references on the panel it closes again the panel.

Unfortunately two new problems arise:
1. Now the message (error/ok) does not disappear when something was saved in another panel
2. The tags are not displayed correct anymore after saving. the nice new layout disappears and only string value is shown. After a manuel reload the look nice again, so now there is definitly no reload anymore

			<b:accordion expanded-panels="conditions">
				<b:panel id="conditions" title="Matching Kriterien" look="primary" >
					<h:form id="formSaveConditions">
								<b:commandButton id="saveContactData" value="Speichern" update="formSaveContactData" look="primary" action="#{freelancerBean.saveContactData}" />
					</h:form>
				</b:panel>
			</b:accordion>
