### ISSUE TITLE
datepicker / dateTimePicker label missing from taglib

### ISSUE THREAD

**Issue by NicolaIsotta** [TheCoder4eu/BootsFaces-OSP#474]
The "label" attribute is missing from the taglib for these components, so the IDE complains: 
![missing attribute](https://cloud.githubusercontent.com/assets/18428155/17140257/1efc80f4-5348-11e6-888e-2612bae8b213.jpg)
Also, these components does not automatically generate the `<label>` element before. Is this a wanted behavior?

**Comment by stephanrauh** [comment]
It's interesting that two components that are so different suffer from the same bug. We've decided to deprecate the `b:datePicker` in favor of the `b:dateTimePicker`. The new component is every bit as powerful as the old one, but it doesn't require jQueryUI.

Currently, the `label` attribute isn't used by the DatePicker. Nor is it used by the DateTimePicker. That's why your IDE is complaining. It's right :).

I've added support for the label to `b:dateTimePicker` this evening. Along the way, I've noticed that the component should always be embedded by `<div class="form-group">`. If you prefer inline forms, it should also be embedded in a `<div class="form-inline">`. You did this in your example manually, but that should be code generated by the component itself. Do you agree?

**Comment by NicolaIsotta** [comment]
> Currently, the  label  attribute isn't used by the DatePicker. Nor is it used by the DateTimePicker. That's why your IDE is complaining. It's right :).

Actually, it's used by validation messages (that's why I thought it was missing from taglib).

> Along the way, I've noticed that the component should always be embedded by  `<div class="form-group">`. If you prefer inline forms, it should also be embedded in a `<div class="form-inline">`. You did this in your example manually, but that should be code generated by the component itself. Do you agree?

Yep.

Another thing. I've noticed the `<input>` generated part of the dateTimePicker doesn't allow direct keyboard input because of the z-index. Is this wanted? And is it possible to clear the `<input>` value?

**Comment by stephanrauh** [comment]
Keyboard input should be allowed. Let's see what we can do about it.

**Comment by NicolaIsotta** [comment]
I forgot to add keyboard input doesn't work if the component is inside a `p:dialog`. IDK if it works with `b:modal` because I'm stuck with `p:dialog` for validation.

**Comment by stephanrauh** [comment]
I've tried to investigate the z-index. As far as I can see, the z-index of prime:dialog is in the 1002 range. The z-index of the dateTimePicker is set to 2 in the core.css (i.e. a Bootstrap file). I take it raising the z-index to - say- 2000 should do the trick? We did this for b:datePicker (see https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/gradleResources/staticResources/css/bsf.css, lines 35ff).

**Comment by NicolaIsotta** [comment]
Setting the z-index to 2000 would cause this:
![2000](https://cloud.githubusercontent.com/assets/18428155/17208874/ba61c0a4-54ba-11e6-9169-1d7006acff4e.jpg)

**Comment by NicolaIsotta** [comment]
This can be closed @stephanrauh @TheCoder4eu

**Comment by stephanrauh** [comment]
I think so, too.
