### ISSUE TITLE
Required fields break ajax update event 

### ISSUE THREAD

**Issue by ScreamingTree86** [TheCoder4eu/BootsFaces-OSP#477]
Hi,
i have a form with some required b:inputfields, an primefaces datatable and a b:selectonemenu. 

`<b:selectOneMenu id="headgroups" value="#{newCirculationView.selectedHeadGroup}" update="form:group_table" onchange="ajax:newCirculationView.setSelectedHeadgroup()">
    <f:selectItems value="#{newCirculationView.headGroups}"/>
</b:selectOneMenu>`

So onChange the Dropdown menu changes the datatable content and afterwards it should be updated. In Bootsfaces Version 0.8.1 this worked. But now i updated to 0.9.1 and as long as the required fields are empty the ajax call is performed but in the browser console i see this `{"validationFailed":true}` and no change is done at the table. 
I tried to add `immediate="true"` at the selectOneMenu but i also get this error. Only if the required fields are filled, the ajax call works. 

Any suggestions how i can get this to work? Maybe this is related to #376 

€dit: I tried to get back to version 0.8.6, but the problem is also there. Seems to be an change between version 0.8.1 and 0.8.6  which causes the problem.

**Comment by stephanrauh** [comment]
Actually, the behavior you describe seems to be what JSF prescribes. I don't like the fact that you can't call a server-side method as long as there's a violated validation constraint, but that's how JSF works. It's strange that BootsFaces 0.8.1 didn't follow this paradigm. In theory, we could try to find a way to circumvent the limitations of the JSF lifecycle, but I doubt JSF developers will appreciate that. Plus, I don't think that's possible (unless by re-implementing the bug that was obviously present in BF 0.8.1 - but that probably only sends the value of the `b:selectOneMenu` to the server, ignoring the other input fields).

BTW, adding `immediate` to the `b:selectOneMenu` doesn't do anything, because we didn't implement the `immediate` flag yet for input fields. It only works for classes deriving from `ActionSource`. That's a surprisingly long list, but it doesn't include any input field:
![image](https://cloud.githubusercontent.com/assets/3045767/17225895/16dc9092-5507-11e6-98d8-c5a5a6a5fcbd.png)

I can think of a couple of workarounds:
* Put the `b:inputFields` into a different form. 
* Ask us to implement something like the partial submit of PrimeFaces.
* Use the PrimeFaces p:selectOneMenu together with partial submit.
* Implement the validations in a method instead of declaring them using `required="true"` or `@NotNull`.

**Comment by stephanrauh** [comment]
I guess we can close this ticket.
