### ISSUE TITLE
I want to use BootsFaces to Enterprise Project.

### ISSUE THREAD

**Issue by ragrok** [TheCoder4eu/BootsFaces-OSP#497]
When I explore www.bootsfaces.net, find BootsFaces can't provide User guide document. so, I can't  persuade my other project member, Can you provide User guide document like other JSF project , like Primefaces.

**Comment by zhedar** [comment]
Well proably the biggest difference between our project and PrimeFaces is, that the latter is backed up by a whole company, PrimeTek. We are consisting of a small team, without providing any commercial support and therefore doing all work on a voluntary basis in our leisure time. Writing and even more maintaining such a document may be too much work, if we're also having a [Showcase](http://showcase.bootsfaces.net) which provides a lot of examples, explanations and some reasoning behind some decisions. 

So while I'm not saying, such a thing won't happen in the near future, it's not very likely. Especially because it would mean to stop or slow down development (atleast if you want a big manual). Commercial support in general however may be possible eventually, but currently we can't guarantee to provide it some time.

*Note that is primarily my own opinion and I didn't speak with the other team members before writing this.*

**Comment by stephanrauh** [comment]
I agree with @zhedar. Currently, I don't see any point in writing a book. I'd rather spend my limited time improving the showcase.

**Comment by ragrok** [comment]
@zhedar @stephanrauh Ok, I konw.

**Comment by ragrok** [comment]
Yeah, I will realize a simple project(use BootsFaces) show other members. It's better If them agree to use it.

**Comment by stephanrauh** [comment]
One day or another, we should write a user guide, but currently, I see little value in leaving this issue open. We'll keep the idea in mind.
