### ISSUE TITLE
execute action when click b:navLink

### ISSUE THREAD

**Issue by sergio11** [TheCoder4eu/BootsFaces-OSP#530]
Hi,

I wanted to know what is the correct way to perform an action when click into nav link. 
because when I set up a navlink in this way the action is not executed:

`<b:navLink iconAwesome="sign-out" value="#{i18n['page.navbar.dropdown.logout']}" action="#{authBean.logout()}"></b:navLink>`

If I use a navCommandLink if it works but I have to use a `<h: form>` in this way:

```
<b:navbarLinks pull="right">
            <h:form>
                <b:dropMenu value="#{user.name} - #{user.lastname}" icon-awesome="user" iconAlign="left">
                    <b:navCommandLink iconAwesome="sign-out" value="#{i18n['page.navbar.dropdown.logout']}" action="#{authBean.logout()}"></b:navCommandLink>
                </b:dropMenu>
            </h:form>
        </b:navbarLinks>
```
This causes the dropdown look bad:
![error](https://cloud.githubusercontent.com/assets/6996211/19645200/df45ea20-99f3-11e6-898a-6f14b2a9895c.PNG)

How could I fix this?

Thanks and greetings

**Comment by zhedar** [comment]
Without trying this myself first: Did you try to put the `h:form` outside the `b:navbar`-tag?
Do you want to use a navbar in this case at all?

My guess is, that a solitary link was created, since the `h:form` disturbs the nav nesting.

**Comment by stephanrauh** [comment]
Like @zhedar mentioned, actions are usually associated with forms, which means you have to use the `b:navCommandLink`. Plus, you have to wrap your `b:navCommandLink` in an HTML `h:form`. Best you wrap your entire navBar in a form, instead of wrapping the individual command links in a form. This should solve your rendering problem.

BTW, I've just fixed a nasty bug with `b:navLink`, which may - maybe - also solve your problem. See #369 on how to get the latest developer snapshot of BootsFaces.
