### ISSUE TITLE
min / max date and special dates in datepicker

### ISSUE THREAD

**Issue by sescde** [TheCoder4eu/BootsFaces-OSP#539]
Is there any chance or workaround to set min and max date for datepicker and / or to exclude special dates?

**Comment by zhedar** [comment]
There is the (currently undocumented) option to set a min / max date by providing the attributes `minDate` and/or `maxDate`, which can be parsed to a valid date. I left off implementing those fields officially, because I couldn't fit it right into our library generator tool, but I'm looking into that again.

**Comment by zhedar** [comment]
I'm closing this in favor of #144 and #538. Progress is tracked there.
