### ISSUE TITLE
Property iconAwesome inside a b:navCommandLink

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#549]
Hi,

The 'iconAwesome' property inside a b:navCommandLink does not seem to work. If instead I put the icon using the b:iconAwesome so this way it works. 

Please, see the examples bellow (with images):

Example (that doesn't work):
<b:navCommandLink iconAwesome="remove">
</b:navCommandLink>
![image](https://cloud.githubusercontent.com/assets/4307334/20277155/839fc134-aa86-11e6-933b-2ca72492cdea.png)

Example (that works):
<b:navCommandLink>
<b:iconAwesome name="remove"/>
</b:navCommandLink>
![image](https://cloud.githubusercontent.com/assets/4307334/20277103/5a1fda38-aa86-11e6-9ef7-c7e1c4620b54.png)

I've also tested with b:navLink and it worked in both cases, the problem seems to be only in a b:navCommandLink.

Ruan

**Comment by asterd** [comment]
Hi @ruanfelisky, actually, to render the navCommandLink or navLink you need to specify a value or a child of the component (this is why with the <b:iconAwesome> child component the rendering works). This is because the component expects at least a value. A rapid fix will be specify a value attribute with an empty string (for example <b:navCommandLink iconAwesome="remove" value=" "/>). This trick will fix your problem. Asap we can think on how to bypass this problem. @stephanrauh  maybe can be a good idea to render HTML even if an icon was specified, isn't it?

**Comment by ruanfelisky** [comment]
Hi @asterd , I've tested according to your suggestion and it solved the problem.

Thanks!

**Comment by stephanrauh** [comment]
We've been so busy recently that we ceased to close solved issues :). I'm closing this ticket now.
