### ISSUE TITLE
Customizing b:inputText type="email" message

### ISSUE THREAD

**Issue by rosese-1** [TheCoder4eu/BootsFaces-OSP#57]
I am looking for a solution to translate the message shown if the user fails to input proper email. It says now "Please enter an email address". I would like to get that in different language. Is that possible somehow?

Best regards
Peter

**Comment by stephanrauh** [comment]
Yes, it's possible. 

* Do you use a browser that's HTML5-ready? In this case, you may see an error message generated by the browser. Set the browser language to your target language (which is the default configuration of your customer), and you're done.

* Is it a Bean Validation API error message? In this case, you can provide your own resource bundle. The easiest (but most inflexible) way is to add the desired error message to the JSF303 annotation.

* Is it an JSF error message? In this case you can modify error messages by providing a resource bundle. Unfortunately, it's not the same resource bundle than in the Bean Validation API case.

In any case, I recommend adding AngularFaces to your project. AngularFaces improves the internationalization support of JSF. The only drawback - if it is one - is it adds AngularJS to your project. See http://angularfaces.com/index.html#/step-02.html and http://angularfaces.com/index.html#/step-01.html.

**Comment by stephanrauh** [comment]
As there's no follow-up question, I assume the issue can be closed.

**Comment by rosese-1** [comment]
Thanks for your reply, it is really appreciated. Sorry it took a while to process that because I am not that familiar with the JSF internationalization. I find BootsFaces very useful for my current project which involves user guidance in Finnish and Swedish. I will look into AngularFaces as you suggest, I believe I can find something out through there. Could you give any hints how I could take benefit of that resource bundle option because that could be quickiest way in this simple project. This is part I would to like translate:
![screenshot](https://cloud.githubusercontent.com/assets/10977099/6219438/fca8e4c0-b631-11e4-8e35-bcf368cf720c.png)

**Comment by stephanrauh** [comment]
I take it you're using Firefox? Because we didn't implement such a fancy tooltip :).

The tooltip is generated by the browser. To see this, create a simple HTML file like this one:
```html
<html>
  <form>
    <input type="email">
  </form>
</html>
```
Invalid e-mail adresses are displayed in a German installation of Firefox like so:
![image](https://cloud.githubusercontent.com/assets/3045767/6219982/d298c1f6-b630-11e4-90db-51bf9a3f97a6.png)

In theory, it should be possible to change the language of Firefox using the switch below (see https://support.mozilla.org/en-US/questions/1018686). But it didn't work on my machine.
![image](https://cloud.githubusercontent.com/assets/3045767/6220079/da9682a2-b631-11e4-8f7a-247600b708ab.png)


By the way, the same message is displayed in Google Chrome slightly differently (and the languages can be changed easily!):
![image](https://cloud.githubusercontent.com/assets/3045767/6219972/b2b128ec-b630-11e4-90a0-0cfbbd49db55.png)

**Comment by rosese-1** [comment]
Haha, cool cool. I installed Finnish version of the Firefox and now the message showed up in Finnish. The message started to appear when I added type="email" inside <b:inputText tag. So it seems to be some browser based solution to validate those different types. Even IE managed to make a similar message. :-)

Ok, I carry on from here. Thanks for your help so far. I will examine AngularFaces while developing the system.

**Comment by TheCoder4eu** [comment]
Hi, I think FF it's crazy, I would expect client side content and messages
should
be driven from the settings in Preferences -> Content Tab -> Languages ...

Did you try this?

**Comment by rosese-1** [comment]
Ok, I didn't know that but it doesn't matter. I can use the Finnish version as well. Pretty cool feature to have browser supporting input box types.

**Comment by stephanrauh** [comment]
I suppose we can close this ticket. Can we?

**Comment by TheCoder4eu** [comment]
Yes, it's answered.
