### ISSUE TITLE
Allow to order a table with a data-order attribute

### ISSUE THREAD

**Issue by vdelacerda** [TheCoder4eu/BootsFaces-OSP#622]
datables.net has a data-order attribute to order a table by any value despites the cell value.

`<td data-order="1311552000">Mon 25th Jul 11</td>`

Just add
```
String dataOrder = (String) column.getAttributes().get("dataOrder");
if (dataOrder != null && !dataOrder.isEmpty()) {
    rw.writeAttribute("data-order", dataOrder, null);
}
```

to add this enhancement, I have a pull request to this.

**Comment by stephanrauh** [comment]
Thanks! There are just to todos left:

- [ ] document the new feature in the showcase
- [ ] add the property to the BootsFaces.jsfdsl file.

**Comment by stephanrauh** [comment]
Documentation and the entry in the JSFDSL file were already there. Seems the generator plugin has a bug.

**Comment by vdelacerda** [comment]
May I have to add the feature in the showcase ? If so, what is the project ?

**Comment by stephanrauh** [comment]
Your help is welcome, but in this particular case you've discovered a bug that isn't quite the bug it seems to be. As it turns out, we've implemented the data-order attribute some time ago. I don't know what your source code looks like, but currently my IDE even shows an error because you've added a variable that's already there. I don't believe you've submitted such a buggy source code, so it's obvious something weird is going on. We use a plugin to generate most of the JSF components. This plugin has run into trouble some time ago. I don't know for sure, but I suspect the reason is that we've got so many JSF components that the plugin has become to slow. Be that as it may, the plugin starts over and over without ever finishing. This may be the reason why the entries in the *.jsfdsl file never made it into the component and the taglib.

I've removed the plugin from the build-on-save list and added a context menu instead. Now it seems to work. Even if it doesn't: now it's easier to find bugs in the plugin.

If you're interested in using the plugin, here it is: https://github.com/stephanrauh/JSFLibraryGenerator/tree/master/plugins

Now to your original question. The documentation (aka showcase) is here: https://github.com/TheCoder4eu/BootsFacesWeb. Like BootsFaces-OSP, this is a hybrid project supporting both Maven and Gradle.

**Comment by stephanrauh** [comment]
The root cause of the generator problem was a directory that already existed with a difference case.

**Comment by stephanrauh** [comment]
@vdelacerda I've just uploaded a new version of BootsFaces-1.1.0-SNAPSHOT to Maven Central. See #369 on how to get it. Please run a quick check if your issue has been solved.

The showcase demonstrates the feature at http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf. Scroll to "customizing the table". The column "age" is displayed as a string but sorted numerically. A few lines below I've explained the feature. Feel free to give us feedback if there's something to improve.

Thanks! Both for contributing a pull request and for nudging me to fix my IDE setup!
Stephan

**Comment by stephanrauh** [comment]
BootsFaces is a long-term project, too, so it's a good match :).

A tout a l'heur
Stephan
