### ISSUE TITLE
b:commandLink

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#652]
i looked at b:button and b:commandButton and neither have a target or href attribute as far as i could see.  this is useful if you want to open something in a new tab.  maybe this could be a superclass of commandLink?
btw where do i register interest in helping with the project?  i have a couple of other things to mention about the documentation which i might be able to help with
- it would be nice if it was ordered alphabetically as it is hard to scan for a 
- if there were links to the source code of the examples directly from the page, or maybe a snippet of the backing bean it would sometimes help to understand the use case

**Comment by stephanrauh** [comment]
`<b:commandButton>` doesn't need either attribute because it's meant to call JSF actions. However, it might be a good idea to add these attributes to `<b:button>`.  Actually, I'm surprised we didn't implement it yet.

As for contributing: simply drop us a mail at "webmaster1 at beyondjava dot de". Like you, I think there's a lot to improve with our showcase :). Instead of sorting stuff alphabetically I'd prefer to offer a search field. Same idea, just differently implemented.

**Comment by stephanrauh** [comment]
Thanks for providing a pull request!
