### ISSUE TITLE
b:dataTableColumn data-order with java.util.Date

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#653]
if data-order on b:dataTableColumn is set to a java.util.Date then it doesn't seem to order properly.  i have tried setting data-type to date.  maybe it could check for Date type and do the ordering automatically

**Comment by chongma** [comment]
Works like #{object.date.time}

**Comment by stephanrauh** [comment]
Auto-detecting the type sounds like a good idea. It'll fail if the table is empty, but then, there's nothing to sort in this case. So your suggestion might work out fine.

**Comment by gtstewart** [comment]
I am having the same problem with sorting dates using the data-order attribute but with a text string in iso format yyyy-MM-dd. It has no affect on the order of the records in the table as they are in the same order as the records in the database table. Only if you click on the sort icon in the table header will they appear in order asc or desc and that order stays active even if the page is re-displayed with different data. Should the sort be triggered on initial display ?.
` <b:dataTableColumn id="dateTransfered" label="Transfer Date" data-order="#{transfers.isoDate}">
                        <h:outputText value="#{transfers.transferDate}" >
                            <f:convertDateTime type="date" pattern="dd/MM/yyyy"></f:convertDateTime>
                        </h:outputText>
                    </b:dataTableColumn>`
the bean function 
` public String getIsoDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return (sdf.format(transferDate));
    }`

the page source code showing the table
`	<tbody>
		<tr role="row" class="odd">
			<td data-order="2016-06-08">08/06/2016</td><td>104</td><td>0</td><td>To Ewe 1</td>
		</tr>
		<tr role="row" class="even">
			<td data-order="2016-06-09">09/06/2016</td><td>98</td><td>0</td><td>Yellow tag to from ewes</td>
		</tr>
		<tr role="row" class="odd">
			<td data-order="2016-11-14">14/11/2016</td><td>0</td><td>200</td><td>To 2016 mature ewes</td>
		</tr>
		<tr role="row" class="even">
			<td data-order="2016-09-01">01/09/2016</td><td>197</td><td>0</td><td>Lambs marked</td>
		</tr>
		<tr role="row" class="odd">
			<td data-order="2016-11-14">14/11/2016</td><td>0</td><td>197</td><td>Lambs weaned</td>
		</tr>
	</tbody>`

I have two tables from different child tables on this page, one is in order only because I set the order on parent entity collection.
`    @OrderBy("movementDate ASC")
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "mobId", fetch = FetchType.LAZY)
    private Collection<MobMovement> mobMovementCollection;`

**Comment by chongma** [comment]
i think a workaround is to use `#{object.date.time}` in the `data-order`

**Comment by stephanrauh** [comment]
I've added this trick to the documentation. The datatable class is already so big, we don't need additional complexity. :)
