### ISSUE TITLE
b:inputText with ajax="true" loses focus after update

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#680]
This is somewhat related to #678. When using <b:inputText value="#{...}" ajax="true" />, every key that is pressed results in an AJAX request, rerendering the whole form and losing input focus.

Two workarounds I see:
* Set the update attribute to something that does not contain the input
* Add an ajax oncomplete callback to regain focus.

**Comment by stephanrauh** [comment]
Probably this bug and the previous bugs can be fixed by defining the correct default action in the JSF component class.
>
>

**Comment by stephanrauh** [comment]
What's a sensible default event setting? `onblur`? `onchange`?

Tentatively, I'' set it to `onblur` because that solves the focus problem.

**Comment by stephanrauh** [comment]
I've uploaded a new developer snapshot to Maven Central. See #369 on how to get it. I'll close this issue, but keep listening to the comments. If the issue turned out not to be solved, don't hesitate to re-open it.

**Comment by ggam** [comment]
I've tested it and it works, but I personally prefer the previous behaviour, as now I have to move the focus out of the field.

Would it be possible to just regain focus? Or is it too difficult for now?

**Comment by stephanrauh** [comment]
Yes, regaining the focus is almost impossible. Or rather, it's difficult to do it right. Mind you, it's easy to regain the focus. But then, you'd also regain the focus when the user hits the TAB key. And what happens if the user uses the cursor keys to navigate within the field? The field is replaced when the `onkeyup` event triggers. That, in turn, means that the cursor is not where the user wants it to be. And I didn't even talk about marking the content :).

BTW, you can easily restore the old functionality by using the `onkeyup` property. I don't know what you do with the AJAX request now. Most likely there's a Java bean method you're calling? If so, just write `onkeyup="ajax:myBean.myMethod()"` to call the method after every keystroke.

**Comment by NicolaIsotta** [comment]
The h:inputText default event in mojarra is change. I think It shouldn't have problems with focus too.

**Comment by stephanrauh** [comment]
BTW, I'll align the default event with standard JSF. There, it's "onchange", as you've suggested in #679.

**Comment by stephanrauh** [comment]
@NicolaIsotta Thanks for confirming that. The default event of the JSF class `HtmlInputText` is `valueChange`. That confused me, but you're right, it's obviously no valid HTML.  I've set the default event of `b:inputText`, `b:inputTextarea` and `b:selectOneMenu` to `change` (which is translated to `onchange` in JavaScript).
