### ISSUE TITLE
b:alert icons with flatly theme

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#731]
#650 has been closed and i cannot reopen so i am creating a new issue.  this still does not work on my system and i have created a test to show this in https://github.com/chongma/test choose test->Alert.  you will (hopefully!) see that there is no icon on a b:alert for the flatly theme.  i have set the flatly theme in web.xml.  if you remove the flatly theme declaration it works fine and shows an icon.

**Comment by chongma** [comment]
![2017-04-25-02 48 03-pm](https://cloud.githubusercontent.com/assets/6253322/25386130/9359fb20-29c6-11e7-939e-89936a3b9f9f.png)

**Comment by stephanrauh** [comment]
The icon is there. It just happens to have exactly the same color as the background.

**Comment by stephanrauh** [comment]
@TheCoder4eu Is it possible to generate theme-specific CSS rules with our Gradle script? In this case, a white icon looks great. But this should only apply to the flatly theme, not to the other themes.

**Comment by TheCoder4eu** [comment]
Well , it isn't exactly a bug, but a css issue...
I'll have a look in the Gradle build to see if we can override on a per theme basis.

**Comment by chongma** [comment]
is the icon not provided from the theme?  is it possible to use an icon colour that works for all themes?

**Comment by stephanrauh** [comment]
Changing the icon color possibly amounts to deviate from the Bootstrap default. I'd like to avoid that. I'm fine with it on a per-theme basis, but not generally.

I don't think the icon is provided by the theme. We've hard-coded the name of the icon in the b:alert component. The icon itself is a Glyphicon (or maybe an icon from Font Awesome, I don't remember which).

**Comment by TheCoder4eu** [comment]
@stephanrauh , @chongma , I just committed a solution which will allow for a per-Theme customization of CSS rules that need to be fixed on the themes.

Since the problem was affecting the following Bootswatch Themes:
cosmo, cyborg, darkly, flatly, lumen, readable, sandstone, slate, superhero, yeti,
this is what I done:
- i split the customizations.less file in customizations.less and theme-customizations.less
- I added a bw subfolder in gradleResources/staticResources/less/bw
- this folder contain a subfolder for all the aforementioned themes
- every theme subfolder contains a theme-customizations.less that from now on will contain theme specific customizations (it contains just Alert icons CSS rules for now)

**Comment by chongma** [comment]
Sounds great. Will it be in RC2? Also I wondered if it is possible to specify the theme per page or even per component. It would help for testing especially

**Comment by TheCoder4eu** [comment]
Yes you can see it in the staging showcase
