### ISSUE TITLE
accordion: expanded-panels not working

### ISSUE THREAD

**Issue by kgeis** [TheCoder4eu/BootsFaces-OSP#873]
I am using BootsFaces 1.1.3 with PrimeFaces 6.1. I create an accordion with panels, and I set the expanded-panels attribute on the accordion. The corresponding panel always loads collapsed.

Example:
```
<b:accordion expanded-panels="panel2">
    <b:panel id="panel2" title="Panel 2">
    </b:panel>
</b:accordion>
```

**Comment by kvj2020** [comment]
I have encountered this same issue in 1.2.0 Snapshot.  I am not using PrimeFaces. I believe the issue only occurs when the accordion is wrapped inside an h:form.  If the form is removed the expansion works properly.

**Comment by TheCoder4eu** [comment]
@kgeis did you try what @kvj2020 suggested?

**Comment by kgeis** [comment]
@TheCoder4eu, no, I did not try @kvj2020's suggestion. That would probably make the accordion work, but it would make my form not work...

**Comment by kvj2020** [comment]
I think a valid scenario is to allow accordions inside a form.  I was commenting on what was causing the issue rather than identifying a work around.  I would like to use the accordion inside a form.  For a b:panel with an id='panel1' inside a form, the clientId is similar to 'j_id_s_1:panel1'.  When the accordion is not inside a panel the clientId is 'panel1'.

Although I do not know the framework well enough, here are two options
1) In both cases the id is 'panel1'. Change AccordionRender.encodingBegin(...) line 104 
  from:  if (null != expandedIds && expandedIds.contains(_childPane.getClientId()))
  to:  if (null != expandedIds && expandedIds.contains(_childPane.getId()) ?

2) if clientId contains ':' split it and use the second item from the split for the above contains check

**Comment by TheCoder4eu** [comment]
@kvj2020 thanks for the suggested code (option 2) I just applied it and committed.

**Comment by vsvetoslavov** [comment]
This issue is still reproducible in v1.4.2
