### ISSUE TITLE
panelgrid lays out HTML comments

### ISSUE THREAD

**Issue by kgeis** [TheCoder4eu/BootsFaces-OSP#874]
I have a comment between two components in a panel grid. The panel grid does not lay this out correctly. Apparently a cell is allocated for the HTML comment. This is not intuitive.

**Comment by TheCoder4eu** [comment]
Hi @kgeis , what version of BootsFaces are you using?

**Comment by stephanrauh** [comment]
That's one of the oddities of JSF. Comments are added to the JSF component tree. We can't do much about it. It's a general problem. Try this with `h:panelGrid` and you'll see the same problem.

Luckily, there's an official workaround. Put your comment in an `<ui:remove>` block. If your command contains an EL expression, you have to use both `<ui:remove>` and the XML comments. Otherwise the EL expressions are evaluated, causing all kinds of unexpected side effects.

```xml
<b:panelGrid columns="2">
   <b:inputText value="#{visible.input.field}">

   <ui:remove>
     <!--
      <b:inputText value="#{invisible.input.field}">
     -->
   </ui:remove>
  
   <b:inputText value="#{second.visible.input.field}">
</b:panelGrid>

**Comment by ggam** [comment]
@kgeis If you want html comments to be revomed, add the following context param to the web.xml:

```
<context-param>
    <param-name>javax.faces.FACELETS_SKIP_COMMENTS</param-name>
    <param-value>true</param-value>
</context-param>
```

I think that's what you are looking for
