### ISSUE TITLE
JSR375 support

### ISSUE THREAD

**Issue by MichailKachalov** [TheCoder4eu/BootsFaces-OSP#884]
Can't get SecurityContext resource link in BootsFaces 1.1.3.
I try resource injection in managed bean:

`
@Resource
private javax.security.enterprise.SecurityContext securityContext;
`

result is - null (in WildFly 11.0.0.CR1) or InjectionException (in GlassFish 5)

**Comment by ggam** [comment]
SecurityContext is injected via `@Inject`. The `@Resource` annotation is used for JNDI injection of container managed artifacts.

**Comment by MichailKachalov** [comment]
If use `@Inject` in WildFly 11.0.0.CR1 error on deploy phase:

> Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type SecurityContext with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private com.foo.bar.bean.controller.IndexBean.securityContext

In GlassFish 5 it's work

**Comment by ggam** [comment]
WildFly 11 still targets Java EE 7. In order to use JSR 375 you'll need to provide an implementation.

Try adding the following dependency to your pom.xml:
```
<dependency>
    <groupId>org.glassfish.soteria</groupId>
    <artifactId>javax.security.enterprise</artifactId>
    <version>1.0</version>
</dependency>
```

Be aware that GlassFish 5 already provides it so you'll have to either remove the dependency or set its scope to "provided" when deploying to that server.

**Comment by MichailKachalov** [comment]
Thank you very much! It works!

**Comment by ggam** [comment]
Great!
