### ISSUE TITLE
Question: Will Bootstrap 4.0 be supported in future?

### ISSUE THREAD

**Issue by stevekv** [TheCoder4eu/BootsFaces-OSP#895]
Hello,

I was wondering, if bootstrap 4.0 (when it finally reaches release state some day) will be supported by bootsfaces? I expect a lot of work for that. Do you have plans?

Thanks,
steve

**Comment by stephanrauh** [comment]
Yes, we're planning to support it. You're right, it is a lot of work. That's why we didn't announce it yet. Once we do, we have to deliver quickly. BTW, would you like to help us?

**Comment by stevekv** [comment]
I would like to help. What do you need?

**Comment by stephanrauh** [comment]
Drop me an email (webmaster1 at beyondjava.de), or join us on Gitter (https://gitter.im/TheCoder4eu/BootsFaces-OSP). Gitter's been dormant for a while, but this is a good reason to reactivate it.

As for what you can do: whatever you like. Give us inspiration, test our new code, write more test cases (yes, we've finally made up our mind to use a lot of JUnit tests!) or contribute new code.

Oh, and give us hints about what compatibility is going to mean with BootsFaces 2. When I migrated an Angular application from Bootstrap 3 to Bootstrap 4, it worked almost from scratch, so I think we should design BootsFaces 2 as a plugin replacement. On the other hand, Bootstrap 4 introduces so many new ideas and concepts that it's ridiculous to believe we can manage to do so. That's a dilemma. I've observed the troubles the Angular team ran into because they announced breaking changes. I'd like to avoid this kind of problems.

**Comment by m1rc0** [comment]
Are there any news on this?

**Comment by neo7BF** [comment]
Are there any news on this ?  We are in 2019

**Comment by neo7BF** [comment]
Are there any news on this ?  We are in 2019

**Comment by stephanrauh** [comment]
I don't think we'll ever support Bootstrap 4. Almost every BootsFaces contributor has abandoned the project. We've got a working, promising prototype, but not enough developers to finish it.

**Comment by vsvetoslavov** [comment]
@stephanrauh @geopossachs 
What is needed exactly? Are there any specific issues defined?

**Comment by stephanrauh** [comment]
There's a private GitHub repository containing a nucleus of BootsFaces 2. Basically, it's writing everything from scratch again, because otherwise it's difficult to benefit from the improvements of Bootstrap 4. I can invite you as a collaborator if you want to have a look at it.

**Comment by geopossachs** [comment]
@stephanrauh it is possible to work for Bootstrap 4 with [ButterFaces ](https://github.com/ButterFaces/ButterFaces) closer?

**Comment by stephanrauh** [comment]
Well, I've already suggested that some time ago, but as long as we've all got so little time for BootsFaces, a cooperation with Lars won't change anything. Actually, a customer of my employer recently asked me how much it'd cost to complete BootsFacesNext. 

My estimation is roughly 100 or 200 days (based on a 40 hours per week schedule). That's a bit heavy for a leisure-time project. I'd love to acquire this as a commercial project, but that's difficult because it means raising more than 100.000 EUR.

**Comment by dguna** [comment]
Is there any progress? I can help, please let me know whay way.

**Comment by dguna** [comment]
Soory it has to be which way

**Comment by geopossachs** [comment]
hallo @dguna 

the last commit to _BootsFacesNext_ (a private GitHub repository containing a nucleus of BootsFaces 2) was on the 5 May 2018.

What are you missing in the current version of BootsFaces? 
I see in your feed your a using http://www.butterfaces.org/ (https://github.com/ButterFaces/ButterFaces/issues/279)
Does it provide all the things which do you need currently?

https://mdbootstrap.com/docs/standard/bootstrap-5/
https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/
https://blog.getbootstrap.com/2020/09/29/bootstrap-5-alpha-2/
I think a support for Bootstrap 4.x just doesn't make sense for this project in the future

I find out that https://myfaces.apache.org/tobago/ also use bootstrap v4 and v5
(https://github.com/apache/myfaces-tobago/commit/4e3a11e2ba27f3105a419e5ae4248ef91a6235ea) / (https://github.com/apache/myfaces-tobago/commit/601e0f5c0dc8fc5b3e2a06e6ada53dc998ef8a45)

@dguna you can take a look at tobago and write a review for what's missing in your opinion. 
Perhaps we could focus on providing a supplement rather than a wider library for things that already exist somewhere else in future

**Comment by stephanrauh** [comment]
We're also suffering from open source developer burnout. It seems most developers have left JSF for good. New issues and pull request have become rare. On the other hand, the download statistics still show a stable base of 4000 downloads per month.

I believe we need two or three developers to support Bootstrap 4 or 5. Any volunteers?

**Comment by evilCoffeecup** [comment]
Hello, 
i found bootsfaces just recently. I think its truly pretty. Is bootsfaces still being supported and will it get updates? Or did it reach its end of life like richfaces? I am asking because i want to use it in a webapp, but if it wont get any updates in the future i dont think i'll be able to use it. But i would really love to! Its really nice 👍

**Comment by stephanrauh** [comment]
I'd love to see BootsFaces alive again. But at the moment, we're in maintenance mode. We've run out of developers. The latest update is JavaEE 9 compatibility and a security fix - but I'm not sure we've managed to publish this as an official version yet.

That's your opportunity. Would you like to maintain a cute little open source library? It's not difficult, it just requires a fraction of your time!

**Comment by evilCoffeecup** [comment]
What would i have to do? I'm not a super dev with a crazy amount experience. But i dont want to see Bootsfaces dead either, because its so very cute.

**Comment by stephanrauh** [comment]
Not being a super dev is a good start. :) BootsFaces does have its rough edges, but they are few, and I can help you with that. The majority of the code is straight-forward. You'll manage!

I'll give you a quick tour, so you can see the complexity (or the lack of complexity) of our code.

Have a look at this folder: https://github.com/TheCoder4eu/BootsFaces-OSP/tree/master/src/main/java/net/bootsfaces/component. That's every component of BootsFaces. Every component is a folder, so it's easy to find the code you're interested in.

Next, have a look at `<b:accordion>`. The package `net.bootsfaces.component.accordion` contains a couple of files. Focus on the "component" class first: https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/component/accordion/AccordionCore.java. This is a collection of every attribute of the component.

If you're confused about the weird formatting: we're generating the file from https://github.com/TheCoder4eu/BootsFaces-OSP/blob/768ab269d4beae2fe424a3300308d6a309e1d0d2/xtext/BootsFaces.jsfdsl#L84-L100. Ignore the generator for the moment. You'll love it, but now you can simply consider the *.jsfdsl file a very compact description of the component.

Finally, have a look at the renderer. It takes the component objects, reads the attributes, and generates HTML. That's not as nice as Angular or React, but it's straightforward. It's just a bit tedious. Here you are: https://github.com/TheCoder4eu/BootsFaces-OSP/blob/768ab269d4beae2fe424a3300308d6a309e1d0d2/src/main/java/net/bootsfaces/component/accordion/AccordionRenderer.java#L73-L148.

**Comment by stephanrauh** [comment]
As for your responsibilities: as you've noticed, we've been lazy during the last couple of years, so there's little pressure. However, we've got a faithful and even growing community, so I'm sure you'll make several thousand developers happy if you decide to keep the project alive. We've lowered the bar to zero, so it's easy to make people happy. :)

The first thing you need to do is to nudge @TheCoder4eu and me to publish version 1.5.1. That's a small but important security update.

After that, it's up to you. If you're using BootsFaces for you own projects, it's fair to align your efforts to these projects of your's. Add features you need, fix bugs you run into, stuff like this.

I'd also appreciate if you cared about security. And of course, we've got 89 open tickets you can have a look at if you've got some time to spare. However, at the moment, I consider this optional. The developers who've opened the tickets have been waiting for such a long time I'm afraid they've abandoned BootsFaces long ago. But of course, there are good friends of BootsFaces like @sebsoftware who haven't given up yet.


Here are the download figures:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/3045767/181628644-aca2d14d-3a8c-45e6-a48b-313e77f2042e.png">

**Comment by stephanrauh** [comment]
Cutting a long story short: I believe you can join the project with very little effort. I'm ready to support you. It's just I don't want to run the BootsFaces project alone. My other open source project is already eating me up! :)

If you're interested, drop me an email at webmaster1 at beyondjava dot de.

Best regards,
Stephan

**Comment by sebsoftware** [comment]
Sometimes ago I started to port it to Bootstrap 5.

I've added the current development, which was a time ago, as a branch "bs5" to my fork of the repositories.
It is almost working, but it lacks the new features of bs5 and it raises some incompatibilities.

But it may be a good start. Have a look at:

https://github.com/sebsoftware/BootsFaces-OSP/tree/bs5
https://github.com/sebsoftware/BootsFacesWeb/tree/bs5

**Comment by evilCoffeecup** [comment]
Thanks ! I'll look through the links. I'd love to keep bootsfaces alive :) @stephanrauh i dropped an email

**Comment by sebsoftware** [comment]
Some thoughts that came into mind, when testing with Bootstrap 5

- compatibility between Bootsfaces3 and "Bootsfaces5"? Due to the fact that also Bootstrap is incompatible in some points it may be required to be incompatible too with Bootsfaces in some components.
- flex properstes should be added
- font awesome support? Due to the fact that bootsfaces is behind the fontawesome releases and mixing of font awesome 4 and 5 is not possible. Which will be, if you use both of the features. I would recommend to drop the auto include for font awesome like PrimeFaces and put it in the hand of the developer to load the fontawesome icons.
- ....
