### ISSUE TITLE
<b:datepicker> in french format

### ISSUE THREAD

**Issue by maciass2008** [TheCoder4eu/BootsFaces-OSP#925]
i need to display b:datepicker in french format ("dd/mm/yyyy")
I tried using format="dd/mm/yyyy" lang="fr" but it doesn't work
any solution?

**Comment by chongma** [comment]
i think it might be DD/MM/YYYY as it doesn't use the default java date format

**Comment by chongma** [comment]
it uses moment.js format which can be found at http://momentjs.com/docs/#/displaying/format/.  it could probably be explained more prominently in the showcase...

**Comment by maciass2008** [comment]
thanks but "DD/MM/YYYY" doesn't work 
is it possible to overload the style of datepicker? like in this example:
$('.sandbox-container input').datepicker({
	format: "dd/mm/yyyy",
	language: "fr",
	todayBtn: "linked",
	autoclose: true
});

**Comment by stephanrauh** [comment]
We'd like to replace `<b:datePicker>` by `<b:dateTimePicker>` for technical reasons. Plus, I believe `<b:dateTimePicker>` already supports French dates. Would you mind to have a look at the new component and migrate to it? If that's not possible for some reason, please tell us what's blocking you. 

As for your feedback regarding the showcase: Merci beaucoup! We desperately need this sort of feedback in order to improve the documentation!

**Comment by maciass2008** [comment]
<b:dateTimePicker> work fine but i still have a problem when i try to update it inside modal panel.
i send action with <b:commandButton> and i try to update the modal form with the update=":formId"
i retreive data but when i try to click again on dateTimePicker icon to choose another date it doesn't work
any idea?
does the "update" attribute deactivates style and javascript in modal component?!
it's a general problem: i have this same problem with other bootsfaces components

**Comment by stephanrauh** [comment]
Did you manage to solve the problem? I hope you didn't just close the issue because the BootsFaces didn't answer I guess we all had a busy week at work...
