### ISSUE TITLE
dateTimePicker maxDate NullPointerException

### ISSUE THREAD

**Issue by lobo115** [TheCoder4eu/BootsFaces-OSP#927]
Hello, i was using dateTimePicker in Payara 4.1.2 and trying to set maxDate parameter and it give me a java.lang.NullPointerException , but when i change it for minDate  it works perfect, my code is:
`<b:dateTimePicker id="lastdate" 
                                                  show-time="false"
                                                  maxDate="09/25/2018"
                                                  />`

**Comment by stephanrauh** [comment]
Awesome analysis! And a sharp eye, too. I had to look twice to spot the error in the source code!

I've upload a corrected version as BootsFaces-1.2.1-SNAPSHOT to Maven Central. See #369 on how to get it. I'll close the ticket because I'm positive it has been solved, but I'd like to invite you to test it with the developer snapshot. If anything went wrong, feel free to re-open the ticket.

Thanks in advance,
Stephan
