### ISSUE TITLE
Bootsfaces close tab in dynamic tab view 

### ISSUE THREAD

**Issue by primeO** [TheCoder4eu/BootsFaces-OSP#946]
How to close the tab in bootsfaces tab view component . Gone through the demo site but no luck . Any suggestions how to achieve it .

**Comment by stephanrauh** [comment]
Please show me a code snippet. I want to be sure we're talking about the same thing :). What does your JSF page look like, and which tab do you want to close?

**Comment by stephanrauh** [comment]
Ok, got it.

So what's the problem? You can simply delete the tab by deleting the corresponding element of the list. There's no native BootsFaces support because you don't need it.

But you wouldn't ask if you didn't felt precisely that need. Let me guess: you want BootsFaces to draw a "close" icon in the tab, and you want BootsFaces to delete the array item if the "close" button has been clicked?

**Comment by primeO** [comment]
Yes exactly the attribute for close . Iam not finding it on demo site . Whether we should use facet there on tab or any alternative .

Thanks in advance

**Comment by stephanrauh** [comment]
Oops - there seems to be a bug. Facets inside the tab don't "speak" AJAX yet. So the solution is a bit clumsy. Have a look at [this commit](https://github.com/TheCoder4eu/BootsFacesWeb/commit/884d8635cc4875d2a0d4f4db926cd37c47fcc6a1), which adds a closable tab to our showcase.
