### ISSUE TITLE
Add Bootstrap Affix Plugin support

### ISSUE THREAD

**Issue by shafinmahmud** [TheCoder4eu/BootsFaces-OSP#970]
As bootstrap affix plugin is a much popular feature, it should be in Bootsfaces too.

**Comment by stephanrauh** [comment]
Looks interesting and useful indeed.

**Comment by stephanrauh** [comment]
The affix plugin has been dropped in Bootstrap 4, so we won't add it because it'd break future compatibility. However, there seems to be a simple replacement. Quoting from the [Bootstrap4 documentation](https://getbootstrap.com/docs/4.0/migration/#components):

> Dropped the Affix jQuery plugin.
We recommend using position: sticky instead. See the HTML5 Please entry for details and specific polyfill recommendations. One suggestion is to use an @supports rule for implementing it (e.g., @supports (position: sticky) { ... })/
If you were using Affix to apply additional, non-position styles, the polyfills might not support your use case. One option for such uses is the third-party ScrollPos-Styler library.

@shafinmahmud Please check if `style="position:sticky"` does the trick for you (and tell us).

**Comment by stephanrauh** [comment]
I'll close the ticket now because there seems to be a simply alternative.

**Comment by shafinmahmud** [comment]
Yes, `style="position: sticky; top: 0;"` works nice.
And I think you are right about it. As Bootstrap 4 dropped Affix plugin support, we shouldn't support it for temporary.

**Comment by shafinmahmud** [comment]
But one thing to mention `postion:sticky` is something very new and doesn't support a good number of browsers version. Here is the  [compatibility list](https://caniuse.com/#feat=css-sticky)

**Comment by stephanrauh** [comment]
Oops - IE11 doesn't support it. That's a nasty surprise. Somehow, I believed that's an old feature.

**Comment by stephanrauh** [comment]
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.
