### ISSUE TITLE
b:slider2 with decimal number (step) values

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFaces-OSP#976]
I would like to be able to slide in steps of 0.25. Is this a feature you are willing to support? Or should I create a composite component for this?

**Comment by jepsar** [comment]
FYI, I just did a quick hack where I've overloaded the slider2 Core and Renderer class. I've changed the types of the min, max and step attribute to float and that already "worked". Only thing that is not yet handled (of course) is locale based number formatting.

<img width="282" alt="Slider2 with decimal step and value" src="https://user-images.githubusercontent.com/7500178/43087001-08ef4258-8e9f-11e8-90d4-2c86e99c93cb.png">

**Comment by stephanrauh** [comment]
Pull requests are welcome. As far as I remember, I tried to allow for decimal numbers myself, but for some reason I didn't managed to do so. It seems you've got more luck. Go ahead!

**Comment by jepsar** [comment]
@stephanrauh While I'm at it, I'll fix a small bug in determining the default value.

````
		if (v == null) {
			v = max / 2;
			slider.setValue(v);
		}
````

should be:

````
		if (v == null) {
			v = min + (max - min) / 2;
			slider.setValue(v);
		}
````

Do you want me to create a new issue for this?

**Comment by jepsar** [comment]
@stephanrauh working on this issue right now. I see that there is a `precision` attribute which was ment to be used for floating values, but is not used at this moment. Can we deprecate / remove that in favour of a new `formatter` attribute?

See formatter at https://github.com/seiyria/bootstrap-slider#options

**Comment by stephanrauh** [comment]
@jepsar Sure. There's no point in keeping an attribute we don't use anyways. Just one thing: the attribute `formatter` is a JavaScript callback function, at least in the seiyria lib. That's great for advanced users, but it may confuse all those developers loving BootsFaces because the don't have to learn JS and CSS. So I'd like to see an easy-entry option, something everybody understands at first glance. Once we've got that, I'd also love to see an advanced option such as a JS callback.

Did you already install the Eclipse plugin to generate the source codes from the BootsFaces.jsfdsl file? If not, add your attributes to the BootsFaces.jsfdsl file, so I can generate the source codes for you.
